---
apiVersion: v1
kind: Namespace
metadata:
  name: big-monolith
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: big-monolith
  name: secret-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"] # all the resources
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: big-monolith
subjects:
# Kubernetes service account
- kind: ServiceAccount
  name: big-monolith-sa
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: big-monolith-sa
    namespace: big-monolith
---
apiVersion: v1
kind: Secret
metadata:
  name: vaultapikey
  namespace: big-monolith
type: Opaque
data:
  k8svaultapikey: azhzLWdvYXQtODUwNTc4NDZhODA0NmEyNWIzNWYzOGYzYTI2NDlkY2U=
---
apiVersion: v1
kind: Secret
metadata:
  name: webhookapikey
  namespace: big-monolith
type: Opaque
data:
  k8swebhookapikey: azhzLWdvYXQtZGZjZjYzMDUzOTU1M2VjZjk1ODZmZGZkYTE5NjhmZWM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hunger-check-deployment
  namespace: big-monolith
spec:
  selector:
    matchLabels:
      app: hunger-check
  template:
    metadata:
      labels:
        app: hunger-check
    spec:
      serviceAccountName: big-monolith-sa
      containers:
      - name: hunger-check
        image: madhuakula/k8s-goat-hunger-check
        # resources:
        #   limits:
        #     memory: "1000Gi"
        #   requests:
        #     memory: "1000Gi"
        # command: ["stress-ng"]
        # args: ["--vm", "1", "--vm-bytes", "500M", "--vm-hang", "1", "-v"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hunger-check-service
  namespace: big-monolith
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: hunger-check
