baseURL = "http://localhost:1234"
languageCode = "en-us"
title = "Kubernetes Goat"
Paginate = 1000
googleAnalytics = ""
theme = "toc-page"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
  title = "Kubernetes Goat"
  description = "Kubernetes Goat is designed to be an intentionally vulnerable cluster environment to learn and practice Kubernetes security."
  logo = "kubernetes-goat.png"
  copyright = "Kubernetes Goat - Madhu Akula"
  copyrighturl = "https://madhuakula.com"

[social]
  # You can add custom key value pairs here
  Github = "https://github.com/madhuakula/kubernetes-goat"
  Twitter = "https://twitter.com/intent/tweet/?text=Kubernetes%20Goat,%20an%20intentionally%20vulnerable%20by%20design%20training%20platform%20to%20learn%20%23Kubernetes%20Security%20by%20%40madhuakula.%20Check%20it%20out%20&url=https://github.com/madhuakula/kubernetes-goat"
